    - name: install Nginx
      ansible.builtin.yum:
        name:  nginx
        state: latest

    - name: install Nginx
      ansible.builtin.systemd_service:
        state: started
        name:  nginx