- name: install Nginx
  hosts: all
  become: true
  tasks:
    - name: install Nginx
      ansible.builtin.yum:
        name:  nginx
        state: latest

    - name: install Nginx
      ansible.builtin.systemd_service:
        state: started
        name:  nginx

    - name: Testing of Roles
      hosts: all
      become: true
      roles:
       - sample

